CREATE DATABASE IF NOT EXISTS `vacc_now`;
-- DROP SCHEMA IF EXISTS `vacc_now`; -- #this line should always be commented after first installation
CREATE SCHEMA IF NOT EXISTS `vacc_now` DEFAULT CHARACTER SET UTF8MB4 ;
USE `vacc_now` ;
CREATE TABLE IF NOT EXISTS BRANCH(
  BRANCH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  AVAILABLE_VACCINES BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS TIME_SCHEDULE(
  TIME_SCHEDULE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  START bigint,
  END bigint,
  BRANCH_ID BIGINT NOT NULL,
  CONSTRAINT `BRANCH_ID` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCH` (`BRANCH_ID`)
);
CREATE TABLE IF NOT EXISTS CLIENT(
	CLIENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS PAYMENT_METHOD(
	PAYMENT_METHOD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS VACCINATION(
  VACCINATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TIME_SCHEDULE_ID BIGINT NOT NULL UNIQUE,
  CLIENT_ID BIGINT NOT NULL,
  PAYMENT_METHOD_ID BIGINT NOT NULL,
  CONFIRMED BIT(1) DEFAULT 0,
  CONSTRAINT `TIME_SCHEDULE_ID` FOREIGN KEY (`TIME_SCHEDULE_ID`) REFERENCES `TIME_SCHEDULE` (`TIME_SCHEDULE_ID`),
  CONSTRAINT `CLIENT_ID` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`),
  CONSTRAINT `PAYMENT_METHOD_ID` FOREIGN KEY (`PAYMENT_METHOD_ID`) REFERENCES `PAYMENT_METHOD` (`PAYMENT_METHOD_ID`)
);